baseURL: 'https://eliran-turgeman.github.io'
languageCode: 'en-us'
title: 'etCodes'
theme: "papermod"
paginate: 5

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
#     description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Eliran Turgeman
    
    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    comments: true

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "etCodes"
        Content: >
            Welcome to etCodes where I publish software engineering related posts.
    socialIcons:
        - name: github
          url: "https://github.com/Eliran-Turgeman"
        - name: KoFi
          url: "https://ko-fi.com/elirant"
        - name: RsS
          url: "index.xml"
          
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: false
        # noClasses: false
#         style: monokai


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
