- name: Send Email Action (Node)
  uses: wadeww/send-email-action@v1
  with:
    # URL of SMTP server
    server_address: smtp.gmail.com
    # Server port
    port: 465
    # Auth username: Use secret
    username: ${{secrets.MAIL_USERNAME}}
    # Auth password: Use secret
    password: ${{secrets.MAIL_PASSWORD}}
    # Sender email address
    from: ${{secrets.SENDER_MAIL}}
    # Comma-separated recipient list
    to: ${{secrets.MAIL_SUBS}}
    # Email subject line
    subject: New post from Eliran
    # Email body text
    body: Read the latest post published at https://eliran-turgeman.github.io/
